[2024-04-24T18:07:44.806+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-24T18:07:44.827+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_task_dag.load_warehouse manual__2024-04-24T18:07:11.774523+00:00 [queued]>
[2024-04-24T18:07:44.833+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_task_dag.load_warehouse manual__2024-04-24T18:07:11.774523+00:00 [queued]>
[2024-04-24T18:07:44.833+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-24T18:07:44.845+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_warehouse> on 2024-04-24 18:07:11.774523+00:00
[2024-04-24T18:07:44.858+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_task_dag', 'load_warehouse', 'manual__2024-04-24T18:07:11.774523+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/DataMLOps.py', '--cfg-path', '/tmp/tmp9k5w1o2a']
[2024-04-24T18:07:44.859+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask load_warehouse
[2024-04-24T18:07:44.861+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=629) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-24T18:07:44.861+0000] {standard_task_runner.py:63} INFO - Started process 644 to run task
[2024-04-24T18:07:44.890+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_task_dag.load_warehouse manual__2024-04-24T18:07:11.774523+00:00 [running]> on host 81cd95c93a08
[2024-04-24T18:07:44.951+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_task_dag' AIRFLOW_CTX_TASK_ID='load_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T18:07:11.774523+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-24T18:07:11.774523+00:00'
[2024-04-24T18:07:44.952+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-24T18:07:45.088+0000] {logging_mixin.py:188} INFO - Database 'bt4301_gp_datawarehouse' already exists. No need to create it.
[2024-04-24T18:07:45.095+0000] {logging_mixin.py:188} INFO - MySQL connection is closed
[2024-04-24T18:07:45.623+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/DataMLOps.py:477 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-04-24T18:07:49.368+0000] {logging_mixin.py:188} WARNING - 2024-04-24 18:07:49.367 
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /home/***/.local/bin/*** [ARGUMENTS]
[2024-04-24T18:07:51.148+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-24T18:07:51.149+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-24T18:07:51.155+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=daily_task_dag, task_id=load_warehouse, execution_date=20240424T180711, start_date=20240424T180744, end_date=20240424T180751
[2024-04-24T18:07:51.198+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-24T18:07:51.218+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-24T18:07:51.221+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
